-- +--------------------------------------------------------------------+
-- | Copyright CiviCRM LLC. All rights reserved.                        |
-- |                                                                    |
-- | This work is published under the GNU AGPLv3 license with some      |
-- | permitted exceptions and without any warranty. For full license    |
-- | and copyright information, see https://civicrm.org/licensing       |
-- +--------------------------------------------------------------------+
--
-- Generated from schema.tpl
-- DO NOT EDIT.  Generated by CRM_Core_CodeGen
--
-- /*******************************************************
-- *
-- * Clean up the existing tables - this section generated from drop.tpl
-- *
-- *******************************************************/

SET FOREIGN_KEY_CHECKS=0;

DROP TABLE IF EXISTS `civicrm_contact_email_engagement`;

SET FOREIGN_KEY_CHECKS=1;

-- /*******************************************************
-- *
-- * Create new tables
-- *
-- *******************************************************/

-- /*******************************************************
-- *
-- * civicrm_contact_email_engagement
-- *
-- * Email engagement data for CiviCRM contacts
-- *
-- *******************************************************/
CREATE TABLE `civicrm_contact_email_engagement` (
  `id` int unsigned NOT NULL AUTO_INCREMENT COMMENT 'Unique ContactEmailEngagement ID',
  `contact_id` int unsigned COMMENT 'FK to Contact',
  `date_last_click` timestamp NULL COMMENT 'Date of last relevant email clickthrough',
  `date_first_click` timestamp NULL COMMENT 'Date of first relevant email clickthrough',
  `date_calculated` timestamp NULL COMMENT 'Date of last calculation of email engagement values',
  `volume` int unsigned COMMENT 'Number of clickthroughs in reporting period',
  `volume_last_30_days` int unsigned COMMENT 'Number of clickthroughs in last 30 days',
  PRIMARY KEY (`id`),
  CONSTRAINT FK_civicrm_contact_email_engagement_contact_id FOREIGN KEY (`contact_id`) REFERENCES `civicrm_contact`(`id`) ON DELETE CASCADE)
ENGINE=InnoDB;
